### ISSUE TITLE
Tilequeue seed should take into account the planet edge

### ISSUE THREAD

**Issue by ambientlight** [tilezen/tilequeue#195]
I am generating seed for Fiji.

<img width="497" alt="screen shot 2017-05-01 at 11 56 27 pm" src="https://cloud.githubusercontent.com/assets/14032724/25584777/fba24158-2ec9-11e7-8a9e-a50be5adeadc.png">

The interesting part here is that LL longitude is 176, while UR longitude is already on the other side of the planet with -178.

I can specify the two separate bounding boxes in seed, but technically this one should be handled correctly straight away

```yaml
# Specify any number of custom bounding boxes to seed tiles for.
    custom:
      zoom-start: 9
      zoom-until: 16

      # Must be set to an array of bounding boxes in `[left, bottom, right,
      # top]` (or `[min lon, min lat, max lon, max lat]`) format
      bboxes: [[176.5360, -19.3056, -178.3113, -15.8711]]
```  

Instead such seed will fail with
```
AssertionError: Invalid bbox. 176.536 not less than -178.3113
```

I guess I can later do a PR for this...
