### ISSUE TITLE
simplify_start?

### ISSUE THREAD

**Issue by pnorman** [tilezen/tilequeue#264]
tilequeue/command.py contains the python

https://github.com/tilezen/tilequeue/blob/master/tilequeue/command.py#L494-L507
```py
        layer_datum = dict(
...
            simplify_start=layer_config.get('simplify_start', 0),
...)
```

I can't find any documentation on what tilequeue/tileserver does with this, or any other references of `simplify_start` in their code.

**Comment by zerebubuth** [comment]
Apologies for the confusion! It's added to the layer datum so that it can be [used in `vector-datasource`](https://github.com/tilezen/vector-datasource/blob/b90a50f532b6381770fd4a8a5ec5e49ee46ebc3b/vectordatasource/transform.py#L3794) to control whether to apply simplification to the geometry at a particular zoom or not.

I agree we should add a comment explaining that. Is there anything else we can do to make that bit of code easier to understand?

**Comment by pnorman** [comment]
I think there's two things
- Add a comment above the section, explaining that these are being made available to the functions in the `transform` section of that layer in the query-config file
- Make the idea of passing arguments to the transform functions more general

Right now the config is
```yaml
layers:
  water:
    template: water.jinja2
    start_zoom: 0
    geometry_types: [Point, MultiPoint, Polygon, MultiPolygon, LineString, MultiLineString]
    simplify_before_intersect: true
    simplify_start: 9
    transform:
      - function_name
    sort: vectordatasource.sort.water
    area-inclusion-threshold: 1
```

Instead of `simplify_start` being a key under the `water` collection, there could be another one like

```yaml
layers:
  water:
    template: water.jinja2
    ...
    transform-parameters:
      simplify_start: 9
      ...
    transform:
      - function_name
```

And then all of transform-parameters could get passed to the functions, instead of hardcoding vector-datasource logic into tilequeue
